FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["Whey.Server/Whey.Server.csproj", "Whey.Server/"]
COPY ["Whey.Core/Whey.Core.csproj", "Whey.Core/"]
COPY ["Whey.Infra/Whey.Infra.csproj", "Whey.Infra/"]

RUN dotnet restore "Whey.Server/Whey.Server.csproj"

COPY . .
WORKDIR "/src/Whey.Server"
RUN dotnet build "Whey.Server.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Whey.Server.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Whey.Server.dll"]
