// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Whey.Core.Models;
using Whey.Infra.Data;

#nullable disable

namespace Whey.Infra.Migrations
{
    [DbContext(typeof(WheyContext))]
    partial class WheyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Whey.Core.Models.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<Platform, string[]>>("Dependencies")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ETag")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastPolled")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastReleased")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<Platform, string[]>>("ReleaseAssets")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SupportedPlatforms")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "Repo")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Whey.Core.Models.Stats.PackageStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Installs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalInteractions")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TotalInteractions");

                    b.ToTable("PackageStats");
                });

            modelBuilder.Entity("Whey.Core.Models.WheyClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublicKey")
                        .IsUnique();

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
